services:
  frontend:
    container_name: dreamchat-frontend
    build:
      context: .
      dockerfile: Dockerfile
    image: dreamchat:frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - dreamchat-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m
      timeout: 3s
      retries: 3
networks:
  dreamchat-network:
    external: true
