services:
  backend:
    container_name: dreamchat-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: dreamchat:backend
    ports:
      - "5000:5000"
    env_file:
      - .env.production
    environment:
      - INSTANCE_NAME=backend-1
    restart: unless-stopped
    networks:
      - dreamchat-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 1m
      timeout: 3s
      retries: 3
  backend2:
    container_name: dreamchat-backend-2
    build:
      context: .
      dockerfile: Dockerfile
    image: dreamchat:backend
    ports:
      - "5001:5000"
    env_file:
      - .env.production
    environment:
      - INSTANCE_NAME=backend-2
    restart: unless-stopped
    networks:
      - dreamchat-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 1m
      timeout: 3s
      retries: 3

  mongo:
    container_name: dreamchat-mongo
    image: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - dreamchat-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 1m
      timeout: 3s
      retries: 3

  mongo-backup:
    container_name: dreamchat-mongo-backup
    image: mongo
    depends_on:
      - mongo
    volumes:
      - mongo_backup:/backup
    entrypoint: >
      bash -c "
        while true; do
          mongodump --uri=mongodb://mongo:27017/dreamchat --out=/backup/$(date +%Y%m%d_%H%M%S);
          find /backup -maxdepth 1 -type d -mtime +7 -exec rm -rf {} \;
          sleep 86400;
        done
      "
      
    networks:
      - dreamchat-network

volumes:
  mongo-data:
  mongo_backup:

networks:
  dreamchat-network:
    external: true



