name: Build and Push Nginx Reverse Proxy

on:
  push:
    paths:
      - 'nginx/**'
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: serkanydn/dreamchat-nginx

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push nginx image
        run: |
          docker build -t $IMAGE_NAME:latest ./nginx
          docker push $IMAGE_NAME:latest
