services:
  nginx:
    image: nginx:alpine
    container_name: dreamchat-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - dreamchat-network

networks:
  dreamchat-network:
    external: true
